apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-passport-gateway.fullname" . }}
  labels:
    {{- include "agent-passport-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "agent-passport-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
